### ISSUE TITLE
5조

### ISSUE THREAD

**Issue by leesoo7595** [fastGithubSchool/fastGit#1]
- [ ] 과업 정하기
- [ ] 과업 나누기
- [x] 과업 해내기 @kahee 
- [ ] 집에 가기 @kahee 
- [x] 조 브런치 생성하기

**Comment by kahee** [comment]
@leesoo7595 이수님 잘하겠습니다 ㅋㅋㅋ

**Comment by kahee** [comment]
@leesoo7595

**Comment by kahee** [comment]
@leesoo7595

**Comment by leesoo7595** [comment]
@kahee
- [ ] git study

**Comment by DongbeenSeo** [comment]
git 협업 실습

**Comment by leesoo7595** [comment]
조 브런치 생성하기 finish

**Comment by orca9s** [comment]
@gambler1541

**Comment by leesoo7595** [comment]
연습연습
