### ISSUE TITLE
6조 Be Social 저희가 하니깐 눈독 들이지 마십쇼

### ISSUE THREAD

**Issue by Younlab** [fastGithubSchool/fastGit#8]
- [ ] 과업 정하기

- [ ] 과업 나누기

- [x] 퇴근하기 

- [ ] 6조 브랜치 만들기 @JWYwoo 

- [ ] 번역하기 @KwonSoonWoo 

- [ ] 장고왕 카와희 @kahee 

- [x] 깃황 여쥔

- [ ] 도커잡스 문

**Comment by kahee** [comment]
@Younlab  여기조에 끼고 싶어요

**Comment by JWYwoo** [comment]
@Younlab 선픽가능한가요?

**Comment by KwonSoonWoo** [comment]
여진 센세 ㅠㅠㅠ

**Comment by yeojin-dev** [comment]
#45 PR도 6조 이슈에 해당합니다.
